# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Plugins\SSHRemotePinningUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 50, 121, 20))
        self.label.setObjectName("label")
        self.pinner_ip_txbx = QtWidgets.QLineEdit(Form)
        self.pinner_ip_txbx.setGeometry(QtCore.QRect(150, 50, 113, 28))
        self.pinner_ip_txbx.setObjectName("pinner_ip_txbx")
        self.test_btn = QtWidgets.QPushButton(Form)
        self.test_btn.setGeometry(QtCore.QRect(150, 130, 93, 28))
        self.test_btn.setObjectName("test_btn")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 121, 20))
        self.label_2.setObjectName("label_2")
        self.pinner_username_txbx = QtWidgets.QLineEdit(Form)
        self.pinner_username_txbx.setGeometry(QtCore.QRect(150, 90, 113, 28))
        self.pinner_username_txbx.setObjectName("pinner_username_txbx")
        self.connection_success_lbl = QtWidgets.QLabel(Form)
        self.connection_success_lbl.setGeometry(QtCore.QRect(250, 130, 67, 17))
        self.connection_success_lbl.setText("")
        self.connection_success_lbl.setObjectName("connection_success_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "pinner IP address"))
        self.test_btn.setText(_translate("Form", "test"))
        self.label_2.setText(_translate("Form", "pinner username"))
